version: '3.7'
services:
  server:
    image: emanuelguimaraes23/fut-api:latest
    environment:
      FUT_DATABASE: ${FUT_DATABASE}
      FUT_USER: ${FUT_USER}
      FUT_PASSWORD: ${FUT_PASSWORD}
      SPRING_PROFILES_ACTIVE: production
    ports:
      - '8080:8080'
    networks:
      - fut-production
networks:
  fut-production:
    driver: bridge
